### PR TITLE
Switch HTTP library from requests to httpx

### PR DESCRIPTION
**Pull request by zliang-akamai**
## 📝 Description

This PR switch the Python HTTP library/client from `requests` to `httpx` for better asyncio support for the future development of asyncio related features.

## ✔️ How to Test
`make e2e`

### CODE REVIEW

**Comment by zliang-akamai** [comment]
@lgarber-akamai Do you think we can do that in a separated PR? I think that would be easier to review.

**Comment by lgarber-akamai** [comment]
> @lgarber-akamai Thank you! Do you think we can do that in a separated PR? I think that would be easier to review.

Sounds good to me! Maybe it could turn into a separate ticket (if it hasn't already)?

**Review by ykim-1 — APPROVED** [review]
Looks good, tests pass as expected locally

**Review by lgarber-akamai — APPROVED** [review]
All E2E tests are passing locally, nice work!

**Pull request merged**
